@startuml シーケンス図
hide footbox
actor 客
participant ":料金装置" as 装置
participant ":ボタン" as ボタン
participant ":ベンダー装置" as ベンダー

客 -> 装置: お金を入れる
activate 装置
ボタン -> ベンダー: ボタン押下
activate ベンダー
ベンダー --> 客: ドリンク排出
deactivate 装置
deactivate ベンダー
@enduml
