@startuml ステートマシン図
left to right direction
    state c1 <<choice>>
    state c2 <<choice>>
    メニュー -> c1
    c1 --> 予約と確認 :予約をする
    c1 --> 今の順番 :今の順番を確認する
    予約と確認 --> c2
    c2 --> あなたの順番 :予約情報を登録する
    c2 --> あなたの順番 :予約情報を確認する
    c2 -> メニュー :予約を取り消す
    [*] --> メニュー :システムに接続する
    今の順番 --> [*]
@enduml