@startuml ステートマシン図
' left to right direction
    メニュー --> 予約と確認 :予約をする
    メニュー --> 今の順番 :今の順番を確認する
    予約と確認 -> あなたの順番 :予約情報を登録する
    予約と確認 -> あなたの順番 :予約情報を確認する
    予約と確認 -> メニュー :予約を取り消す
    [*] -right-> メニュー
    メニュー -right-> [*]
@enduml