@startuml オブジェクト図
    object "<u>Aさん:利用者</u>" as A{

    }
    object "<u>Bさん:利用者</u>" as B{

    }
    object "<u>301号室:客室</u>" as 301{
        客室タイプ=シングル
        一泊の宿泊代=11,000
        キャンペーン価格=9,000
    }
    object "<u>302号室:客室</u>" as 302{
        客室タイプ=シングル
        一泊の宿泊代=11,000
        キャンペーン価格=9,000
    }
      object "<u>303号室:客室</u>" as 303{
        客室タイプ=シングル
        一泊の宿泊代=11,000
        キャンペーン価格=9,000
    }
    A -- 301
    B -- 302
@enduml