@startuml クラス図
left to right direction
    class "利用者" as user{
        - 名前
        - 住所
        - 電話番号
    }
    class "ホテル" as ho{
        - 部屋
    }
    class "部屋" as room{
        - タイプ
        - 価格
        - キャンペーン価格
    }
    class "予約" as res{
        - チェックイン日
        - 滞在期間
        - 値段
    }
    ho"1" -- "*"room
    ho"1" -- "*"user
    user"1" -- "*"room
    user"1" -- "1"res

@enduml