@startuml アクティビティ図
title ハンバーガーショップ
|顧客|
|顧客|
|スタッフ|
|スタッフ|
|厨房|
|厨房|

|スタッフ|
start
:挨拶をする;
:注文を聞く;
|スタッフ|

|顧客|
:注文する;
|顧客|

|スタッフ|
:注文を確認する;
|スタッフ|

fork
    |スタッフ|
    :代金を請求する;
    |スタッフ|

    |顧客|
    :代金を払う;
    |顧客|

    |スタッフ|
    :精算する;
fork again
    :商品の調理を依頼する;
    |スタッフ|

    |厨房|
    :商品を料理する;
|スタッフ|
end fork
|スタッフ|
:テイクアウトかどうか尋ねる;
if() then(テイクアウト)
    :袋に入れる;
else(店内)
    :トレイにのせる;
endif
:商品を渡す;
|スタッフ|
|顧客|
:商品を受け取る;
|顧客|
@enduml